# Custom aliases.
alias echopath="echo $PATH | tr ':' '\n'"
alias echofpath="echo $FPATH | tr ':' '\n'"
alias fzfp="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'"
alias ls="lsd"
alias ll="ls -l"
alias la="ls -al"
alias less="less -FRS"
alias make="gmake"
alias py="python"
alias python="python3"
alias vim="vim -u $XDG_CONFIG_HOME/vim/vimrc.vim"
alias vi="vim"
alias wget="curl -LO --retry 999 --retry-max-time 0 -C - "
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/yarnrc"'