# Custom aliases.
alias cat="bat -S"
alias cht="cht.sh"
alias echopath="echo $PATH | tr ':' '\n'"
alias find="fd"
alias fzfp="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {}'"
alias grep="rg"
alias la="lsa"
alias ls="lsd"
alias less="less -FRS"
alias make="gmake"
alias py="python"
alias python="python3"
alias vi="vim"
alias vim="vim -u $XDG_CONFIG_HOME/vim/vimrc.vim"
alias wget="curl -LO --retry 999 --retry-max-time 0 -C - "
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/yarnrc"'